### ISSUE TITLE
1122 开源 TODO

### ISSUE THREAD

**Issue by liuvigongzuoshi** [antvis/L7Plot#74]
### 组件

- [ ] 主题抽离分类
- [ ] l7 zoom scale layerMenu 样式配置化
- [x] tooltip 支持自定组件，暴露组件活动事件
- [ ] 分类图例

### 图表

- [x] choropleth 
	- [x] 描边高亮、支持单选及多选
	- [x] 下钻性能优化
	- [x] 行政数据抽稀，支持 topojson
	- [x] 无值时颜色映射可默认化配置
- [x] line
	- [x] path(trail)
	- [x] flow(arc/connection)

### 文档

- [x] API 补齐
- [ ] API Demo

### Demo

- [x] choropleth
- [x] area
- [x] line
	- [x] trail/path
	- [x] arc/flow/connection
- [x] l7plot
	- [x] muti plot
	- [x] muti layer 	

### 测试

- [x] layers
- [ ] 图表
- [ ] l7plot

### 教程

- [x] 简介
- [x] 快速上手
- [x] #75

### Charts

- [x] 散点
- [x] 热力
- [x] 区域
- [x] 行政

### Workflows

- [x] Build UMD
- [x] Automatic Rebase
- [x] ISSUE_TEMPLATE、PULL_REQUEST_TEMPLATE
- [x] Gitee sync
- [ ] CHANGELOG

**Comment by liuvigongzuoshi** [comment]
fixed #75
